[versions]
minecraft     = "26.1.2"
fabric-loader = "0.18.6"
parchment     = "1.21.10:2025.10.12"
fabric-api    = "0.145.4+26.1.1"

# Compatiblity
yacl          = "3.9.0+26.1-fabric"
controlling   = "XL1X0c1E"
searchables   = "JBRkFpZt"

fabric-loom   = "1.15-SNAPSHOT"

[libraries]
minecraft     = { module = "com.mojang:minecraft"                 , version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader"           , version.ref = "fabric-loader" }
fabric-api    = { module = "net.fabricmc.fabric-api:fabric-api"   , version.ref = "fabric-api" }
yacl          = { module = "dev.isxander:yet-another-config-lib"  , version.ref = "yacl" }
controlling   = { module = "maven.modrinth:controlling"           , version.ref = "controlling" }
searchables   = { module = "maven.modrinth:searchables"           , version.ref = "searchables" }

[plugins]
fabric-loom   = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
